### ISSUE TITLE
Classic support

### ISSUE THREAD

**Issue by paroyer** [GoldpawsStuff/Bagnon_ItemLevel#6]
Would be amazing if the addon was compatible with classic, most seem to work actually just throwing some lua error i suposed are link to api funct not available in classic.

Message: Interface\AddOns\Bagnon_RequiredLevel\main.lua:209: attempt to call upvalue 'GetProfessions' (a nil value)
Time: Wed Sep 30 23:45:04 2020
Count: 1
Stack: Interface\AddOns\Bagnon_RequiredLevel\main.lua:209: attempt to call upvalue 'GetProfessions' (a nil value)
...erface\AddOns\Bagnon\common\Wildpants\api\events.lua:77: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:120: in function <Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: self = <table> {
 SendSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 UpdateBags = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\events.lua:69
 RegisterMessage = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 REAGENTBANK_PURCHASED = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\events.lua:50
 sizes = <table> {
 }
 firstVisit = true
 PLAYERREAGENTBANKSLOTS_CHANGED = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\events.lua:46
 SendMessage = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 UpdateBankBags = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\events.lua:81
 types = <table> {
 }
 UnregisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 UpdateContent = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\events.lua:113
 CACHE_BANK_OPENED = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\events.lua:54
 UpdateSize = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\events.lua:89
 RegisterEvent = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 UpdateType = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\events.lua:103
 queue = <table> {
 }
 UnregisterAllEvents = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 OnEnable = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\events.lua:20
 BAG_UPDATE = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\events.lua:37
 RegisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:74
 NewModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 PLAYERBANKSLOTS_CHANGED = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\api\events.lua:41
 UnregisterEvent = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Tag = "BAGNON_"
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 -2 = true
}
(for control) = 0
bag = 0

**Comment by goldpaw** [comment]
That's a bug report from Bagnon RequiredLevel, a completely different addon. 

Anyway, the bagnon versions in classic and retail are completely different, based on completely different code. It's not a matter of changing a few API calls, it's a matter of writing a completely new addon. I'm not even certain bagnon for classic accepts plugins, at least not in the same easy manner. 

I have no plans of writing any plugins for bagnon for classic. Sorry!
