### ISSUE TITLE
LUA error with latest release.

### ISSUE THREAD

**Issue by Rorthron** [GoldpawsStuff/Bagnon_ItemLevel#9]
Getting this issue today with the latest version Bagnon_ItemLevel-1.0.50-Release-bcc.zip just downloaded from CurseForge. This happens when opening Bagnon

Message: Interface\AddOns\Bagnon_ItemLevel\main.lua:169: attempt to index global 'color' (a nil value)
Time: Mon May 30 18:04:43 2022
Count: 13
Stack: Interface\AddOns\Bagnon_ItemLevel\main.lua:169: attempt to index global 'color' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Bagnon_ItemLevel\main.lua"]:169: in function <Interface\AddOns\Bagnon_ItemLevel\main.lua:100>
[string "=[C]"]: in function `Update'
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\item.lua"]:40: in function <...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:34>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\classes\itemGroup.lua"]:124: in function `func'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0.lua"]:36: in function <...mon\Wildpants\libs\MutexDelay-1.0\MutexDelay-1.0.lua:30>

Locals:

**Comment by Goldpaw** [comment]
Fixed in 1.0.51-Release which should be available shortly!
